publishDir = "docs"
baseURL = "https://ajency.github.io/goomo_html/"
languageCode = "en-us"
title = "Goomo by Ajency"
theme = "goomo"

[menu]
[[menu.main]]
    name = "Dashboard"
    pre = "<i class='fa fa-bars'></i>"
    weight = -110
    identifier = "dashboard"
    url = "#"
[[menu.main]]
    name = "Bookings"
    pre = "<i class='fa fa-calendar-check-o'></i>"
    weight = -100
    identifier = "booking"
    url = "#"
[[menu.main]]
    name = "Reviews"
    pre = "<i class='fa fa-comments-o'></i>"
    weight = -98
    identifier = "review"
    url = "#"
 [[menu.main]]
     name = "Rates & Availability"
     pre = "<i class='fa fa-money'></i>"
     weight = -99
     identifier = "rates-availability"
     url = "#"
[[menu.main]]
    name = "Property Details"
    pre = "<i class='fa fa-list'></i>"
    weight = -97
    identifier = "property-details"
    url = "#"

[[menu.main]]
    name = "Summary"
    parent = "property-details"
    weight = -100
    identifier = "summary"
    url = "#"
    active = true
[[menu.main]]
    name = "Amenities & Services"
    parent = "property-details"
    weight = -98
    identifier = "services"
    url = "#"
[[menu.main]]
    name = "Address & Contact"
    parent = "property-details"
    weight = -95
    identifier = "contact"
    url = "#"
[[menu.main]]
    name = "Images"
    parent = "property-details"
    weight = -90
    identifier = "images"
    url = "#"
[[menu.main]]
    name = "Rooms"
    parent = "property-details"
    weight = -80
    identifier = "rooms"
    url = "#"
[[menu.main]]
    name = "Policies"
    parent = "property-details"
    weight = -75
    identifier = "booking-policy"
    url = "#"
[[menu.main]]
    name = "Audit Logs"
    parent = "property-details"
    weight = -70
    identifier = "audit-logs"
    url = "#"

[[menu.main]]
    name = "Contract & Finance"
    parent = "property-details"
    pre = "<i class='fa fa-address-card-o'></i>"
    weight = -97
    identifier = "finance"
    url = "#"