publishDir = "docs"
baseURL = "https://ajency.github.io/goomo_html/"
languageCode = "en-us"
title = "Goomo by Ajency"
theme = "goomo"

[menu]
[[menu.main]]
    name = "Dashboard"
    pre = "<i class='fa fa-bars'></i>"
    weight = -110
    identifier = "dashboard"
    url = "/"
[[menu.main]]
    name = "Booking"
    pre = "<i class='fa fa-calendar-check-o'></i>"
    weight = -100
    identifier = "booking"
    url = "/booking/"
[[menu.main]]
    name = "Review"
    pre = "<i class='fa fa-comments-o'></i>"
    weight = -99
    identifier = "review"
    url = "/review/"
[[menu.main]]
    name = "Property Details"
    pre = "<i class='fa fa-list'></i>"
    weight = -98
    identifier = "property-details"
    url = "/property/"

[[menu.main]]
    name = "Summary"
    parent = "property-details"
    weight = -100
    identifier = "summary"
    url = "/property/summary/"
[[menu.main]]
    name = "Amenities & Services"
    parent = "property-details"
    weight = -98
    identifier = "services"
    url = "/property/services/"
[[menu.main]]
    name = "Contact & Address"
    parent = "property-details"
    weight = -95
    identifier = "contact"
    url = "/property/contact/"
[[menu.main]]
    name = "Images"
    parent = "property-details"
    weight = -90
    identifier = "images"
    url = "/property/images/"
[[menu.main]]
    name = "Rooms"
    parent = "property-details"
    weight = -80
    identifier = "rooms"
    url = "/property/rooms/"
[[menu.main]]
    name = "Policies"
    parent = "property-details"
    weight = -75
    identifier = "booking-policy"
    url = "/property/booking-policy/"

[[menu.main]]
    name = "Rates & Availability"
    pre = "<i class='fa fa-money'></i>"
    weight = -80
    identifier = "rates-availability"
    url = "/property/rates-availability/"
[[menu.main]]
    name = "Contract & Finance"
    pre = "<i class='fa fa-address-card-o'></i>"
    weight = -70
    identifier = "finance"
    url = "/contract-finance/"